ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS reseller_tier TEXT DEFAULT 'bronze',
  ADD COLUMN IF NOT EXISTS lifetime_spend NUMERIC(10, 2) DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS commission_balance NUMERIC(10, 2) DEFAULT 0.00;

ALTER TABLE services
  ADD COLUMN IF NOT EXISTS min_quantity INTEGER DEFAULT 1,
  ADD COLUMN IF NOT EXISTS max_quantity INTEGER,
  ADD COLUMN IF NOT EXISTS unit_label TEXT DEFAULT 'pcs',
  ADD COLUMN IF NOT EXISTS is_pro BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS smm_service_id TEXT,
  ADD COLUMN IF NOT EXISTS icon_url TEXT,
  ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pricing_model TEXT DEFAULT 'fixed',
  ADD COLUMN IF NOT EXISTS price_per_unit NUMERIC,
  ADD COLUMN IF NOT EXISTS category TEXT;

ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS reseller_discount NUMERIC(10, 2) DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS smm_order_id TEXT;
